### ISSUE TITLE
Have you meet this error?

### ISSUE THREAD

**Issue by liuhl-source** [ChenRocks/UNITER#42]
[1,2]<stderr>:  File "train_itm.py", line 410, in <module>
[1,2]<stderr>:    main(args)
[1,2]<stderr>:  File "train_itm.py", line 221, in main
[1,2]<stderr>:    LOGGER.info(f"image retrieval R1: "
[1,2]<stderr>:KeyError: 'img_r1'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_itm.py", line 410, in <module>
[1,1]<stderr>:    main(args)
[1,1]<stderr>:  File "train_itm.py", line 221, in main
[1,1]<stderr>:    LOGGER.info(f"image retrieval R1: "
[1,1]<stderr>:KeyError: 'img_r1'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "train_itm.py", line 410, in <module>
[1,3]<stderr>:    main(args)
[1,3]<stderr>:  File "train_itm.py", line 221, in main
[1,3]<stderr>:    LOGGER.info(f"image retrieval R1: "
[1,3]<stderr>:KeyError: 'img_r1'
[1,0]<stderr>:
[1,0]<stderr>:10/24/2020 15:08:26 - INFO - __main__ -   evaluation finished in 565 seconds
[1,0]<stderr>:10/24/2020 15:08:26 - INFO - __main__ -   image retrieval R1: 63.73,
[1,0]<stderr>:image retrieval R5: 87.61,
[1,0]<stderr>:image retrieval R10: 93.51
[1,0]<stderr>:text retrieval R1: 74.95,
[1,0]<stderr>:text retrieval R5: 92.70,
[1,0]<stderr>:text retrieval R10: 97.14
[1,0]<stderr>:10/24/2020 15:08:26 - INFO - __main__ -   ==================================================================
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_itm.py", line 410, in <module>
[1,0]<stderr>:    main(args)
[1,0]<stderr>:  File "train_itm.py", line 176, in main
[1,0]<stderr>:    all_reduce_and_rescale_tensors(grads, float(1))
[1,0]<stderr>:  File "/root/paddlejob/workspace/env_run/utils/distributed.py", line 35, in all_reduce_and_rescale_tensors
[1,0]<stderr>:    hvd.allreduce_(buffer_t[:offset])
[1,0]<stderr>:  File "/opt/conda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 252, in allreduce_
[1,0]<stderr>:    handle = allreduce_async_(tensor, average, name, op)
[1,0]<stderr>:  File "/opt/conda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 228, in allreduce_async_
[1,0]<stderr>:    return _allreduce_async(tensor, tensor, name, op)
[1,0]<stderr>:  File "/opt/conda/envs/py36/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 127, in _allreduce_async
[1,0]<stderr>:    name.encode() if name is not None else _NULL, true_op)
[1,0]<stderr>:RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,0]<stderr>:
 10%|#         | 2000/20000 [34:10<5:07:33,  1.03s/it]-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was

  Process name: [[10998,1],3]
  Exit code:    1

**Comment by zh-plus** [comment]
Same issue, any solution?
