### ISSUE TITLE
lmdb.Error: /userhome/UNITER/UNITER/img/coco_train2014/all: No such file or directory

### ISSUE THREAD

**Issue by wangxiao5791509** [ChenRocks/UNITER#80]
(base) root@e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0:/userhome/UNITER/UNITER# rm -rf output && python pretrain.py --config config/pretrain-alldata-base-8gpu.json --output_dir /userhome/UNITER/UNITER/output/
--------------------------------------------------------------------------
[[48719,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
07/15/2021 08:44:23 - INFO - __main__ -   device: cuda:0 n_gpu: 1, rank: 0, 16-bits training: True
07/15/2021 08:44:24 - INFO - __main__ -   Waiting on git info....
07/15/2021 08:44:24 - INFO - __main__ -   Git branch: master
07/15/2021 08:44:24 - INFO - __main__ -   Git SHA: 1dbfa62bb8ddb1f2b11d20775ce324c5e45a3ab4
  0%|                                                                                                                                                            | 0/200000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "pretrain.py", line 642, in <module>
    main(args)
  File "pretrain.py", line 206, in main
    opts.train_datasets, True, opts)
  File "pretrain.py", line 125, in create_dataloaders
    img_db = [all_img_dbs[path] for path in dset['img']]
  File "pretrain.py", line 125, in <listcomp>
    img_db = [all_img_dbs[path] for path in dset['img']]
  File "/userhome/UNITER/UNITER/data/data.py", line 311, in __getitem__
    self.min_bb, self.num_bb, self.compress)
  File "/userhome/UNITER/UNITER/data/data.py", line 75, in __init__
    readahead=not _check_distributed())
lmdb.Error: /userhome/UNITER/UNITER/img/coco_train2014/all: No such file or directory
Exception ignored in: <bound method DetectFeatLmdb.__del__ of <data.data.DetectFeatLmdb object at 0x7f70a2ae57f0>>
Traceback (most recent call last):
  File "/userhome/UNITER/UNITER/data/data.py", line 98, in __del__
    self.env.close()
AttributeError: 'DetectFeatLmdb' object has no attribute 'env'

(base) root@e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0:/userhome/UNITER/UNITER# 
(base) root@e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0:/userhome/UNITER/UNITER# 
(base) root@e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0:/userhome/UNITER/UNITER# 
(base) root@e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0:/userhome/UNITER/UNITER# rm -rf output && python pretrain.py --config config/pretrain-indomain-base-8gpu.json --output_dir /userhome/UNITER/UNITER/output/

--------------------------------------------------------------------------
[[47594,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: e3ff8e900e504011eb09ab60a9de5c5cd03e-wangx3189-0

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
07/15/2021 08:49:38 - INFO - __main__ -   device: cuda:0 n_gpu: 1, rank: 0, 16-bits training: True
07/15/2021 08:49:38 - INFO - __main__ -   Waiting on git info....
07/15/2021 08:49:38 - INFO - __main__ -   Git branch: master
07/15/2021 08:49:38 - INFO - __main__ -   Git SHA: 1dbfa62bb8ddb1f2b11d20775ce324c5e45a3ab4
  0%|                                                                                                                                                            | 0/200000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "pretrain.py", line 642, in <module>
    main(args)
  File "pretrain.py", line 206, in main
    opts.train_datasets, True, opts)
  File "pretrain.py", line 125, in create_dataloaders
    img_db = [all_img_dbs[path] for path in dset['img']]
  File "pretrain.py", line 125, in <listcomp>
    img_db = [all_img_dbs[path] for path in dset['img']]
  File "/userhome/UNITER/UNITER/data/data.py", line 311, in __getitem__
    self.min_bb, self.num_bb, self.compress)
  File "/userhome/UNITER/UNITER/data/data.py", line 75, in __init__
    readahead=not _check_distributed())
**lmdb.Error: /userhome/UNITER/UNITER/img/coco_train2014/all: No such file or directory**
Exception ignored in: <bound method DetectFeatLmdb.__del__ of <data.data.DetectFeatLmdb object at 0x7f640cfec908>>
Traceback (most recent call last):
  File "/userhome/UNITER/UNITER/data/data.py", line 98, in __del__
    self.env.close()
**AttributeError: 'DetectFeatLmdb' object has no attribute 'env'** 

============================================ 
Many bugs in this code. Any plan for the update of this code?

**Comment by cherlw** [comment]
请问您解决了吗？我也碰到了这个问题
