### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'train_datasets'

### ISSUE THREAD

**Issue by ForawardStar** [ChenRocks/UNITER#92]
When I launched the 2nd stage training using :
```
horovodrun -np 4 python pretrain_vcr.py --config config/pretrain-vcr-base-4gpu.json \
    --output_dir $PRETRAIN_VCR_EXP
```
An error occured, which is:

```
Traceback (most recent call last):

File "pretrain_vcr.py", line 560, in <module>

main(args)

File "pretrain_vcr.py", line 205, in main

all_dbs = [db for datasets in [opts.train_datasets, opts.val_datasets]

AttributeError: 'Namespace' object has no attribute 'train_datasets'
```
How to fix this problem? Thanks.

**Comment by linjieli222** [comment]
`train_datasets` is indeed in opts (which is loaded from config)

https://github.com/ChenRocks/UNITER/blob/1dbfa62bb8ddb1f2b11d20775ce324c5e45a3ab4/config/pretrain-vcr-base-4gpu.json#L30

**Comment by ForawardStar** [comment]
Thanks for your reply! It is helpful to me. Here I want to launch the first stage pre-training on COCO, Visual Genome, CC, and SBU. Can your provide the linking for downloading CC, and SBU? If their sizes are too large, can you simply provide the .db file of text input, or the scripts for producing such .db file?
